import "package:get/get_navigation/src/root/internacionalization.dart";

class LocaleString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "hi": {
          "appName": "टेक्निको कार्पोरेशन",
          "login": "लॉग इन करें",
          "email": "ईमेल",
          "password": "पासवर्ड",
          "remember_me": "मुझे याद करो",
          "forgot_password": "पासवर्ड भूल गए",
          "enter_email_address": "ईमेल पता दर्ज करें",
          "enter_valid_email": "मान्य ईमेल दर्ज करें",
          "enter_password": "पास वर्ड दर्ज करें",
          "password_should_be":
              "पासवर्ड में कम से कम 8 अक्षर होने चाहिए, जिसमें कम से कम एक अक्षर होना चाहिए, ऊपर और नीचे के बड़े अक्षरों का एक, 1 विशेष वर्ण और 1 संख्या होनी चाहिए।",
          "create_an_account": "खाता बनाएं",
          "signup": "साइनअप",
          "continue_as_a": "एक रूप में जारी रखें",
          "guest": "अतिथि",
          "OR": "या",
          "name": "नाम",
          "create_account": "खाता बनाएं",
          "confirm_password": "पासवर्ड की पुष्टि करें",
          "serverError": "सर्वर त्रुटि। बाद में पुन: प्रयास करें",
          "accountAlreadyExist": "उस ईमेल के लिए पहले से ही खाता मौजूद है।",
          "accountNotExist": "उस ईमेल के लिए कोई उपयोगकर्ता नहीं मिला।",
          "wrongPassword": "उपयोगकर्ता के लिए गलत पासवर्ड प्रदान किया गया है।",
          "comingSoon": "जल्द ही आ रहा है",
          "home": "होम",
          "news": "समाचार",
          "settings": "सेटिंग्स",
          "search": "खोज",
          "dark_theme": "डार्क थीम",
          "are_you_sure_to_delete_account": "क्या आप खाता हटाना चाहते हैं",
          "are_you_sure_to_log_out": "क्या आप लॉग आउट करना चाहते हैं",
          "it_will_remove_your_all_information": "यह आपकी सभी जानकारी हटा देगा",
          "no": "नहीं",
          "yes": "हाँ",
          "delete_account": "खाता हटाएं",
          "internetIssue":
              "नेटवर्क से कनेक्ट करने का प्रयास करें या बाद में पुन: प्रयास करें",
          "log_out": "लॉग आउट",
          "noInternetImage":
              "कोई इंटरनेट कनेक्शन उपलब्ध नहीं है। स्क्रीन को रीलोड करने के लिए ताजगी दें",
          "noDataFound": "कोई डेटा नहीं मिला",
          "already_have_account": "पहले से ही खाता है",
          "enter_first_name": "पहला नाम दर्ज करें",
          "enter_confirm_password": "पुष्टि पासवर्ड दर्ज करें",
          "password_did_not_match": "पासवर्ड मेल नहीं खाता",
          "error": "त्रुटि",
          "termsAndConditions1": "जारी रखने के लिए आपको सहमत होना चाहिए",
          "termsAndConditions2": " नियम और शर्तें",
          "about_us": "हमारे बारे में",
          "about_us_Head": "टेक्निको कार्पोरेशन",
          "skip": "छोड़ें",
          "loginScreen1": "स्वागत है!",
          "loginScreen2": "कृपया आवेदन शुरू करने के लिए एक प्रोफ़ाइल भरें",
          "loginScreen3": "एक तस्वीर जोड़ें",
          "mobilenumberhint": "फ़ोन नंबर",
          "mobilenumbererror": "फ़ोन नंबर दर्ज करें",
          "editimage": "कृपया अपनी छवि स्रोत का चयन करें:",
          "cameraCapture": "तस्वीर लें",
          "galleryCapture": "अपने गैलरी से चयन करें",
          "buildnamebar1": "आपके पास हैं ",
          "buildnamebar2": "कार्य ",
          "buildnamebar3": "जिसकी रिपोर्ट नहीं की गई है",
          "highTemperature": "40 डिग्री से ऊपर का तापमान",
          "highrain": "बिजलीचमक, 8 मिमी से अधिक वर्षा के साथ तूफान",
          "alert": "चेतावनी: ",
          "weather": "मौसम",
          "sunny": "सूरजमुखी है",
          "rumusan": "संक्षेप",
          "important": "महत्वपूर्ण सामग्री",
          "report": "अब रिपोर्ट करें",
          "laporantugas": "कार्य रिपोर्ट",
          "beritaterkini": "नवीनतम समाचार",
          "pencapaianpetani": "किसान की प्रशंसा",
          "peringtantugas": "कार्य अनुस्मारक",
          "ramalancuaca": "मौसम पूर्वानुमान",
          "jomberbual": "चलो बात करते हैं",
          "logout": "लॉग आउट",
          "returnHomePage": "होम पेज पर वापस जाएं",
          "startconvo": "एक बातचीत शुरू करें",
          "enterSomethingError": "कुछ दर्ज करें",
          "givePermission": "कृपया अनुमति दें",
          "recordingwarning":
              "रिकॉर्ड करने के लिए होल्ड करें, फिर भेजने के लिए दबाएं",
          "beritarasmi": "आधिकारिक",
          "beritalain": "अन्य",
          "beritarasmiShow": "Official",
          "beritalainShow": "Other",
          "morning": "सुबह",
          "evening": "शाम",
          "Monday": "सोमवार",
          "Tuesday": "मंगलवार",
          "Wednesday": "बुधवार",
          "Thursday": "गुरुवार",
          "Friday": "शुक्रवार",
          "Saturday": "शनिवार",
          "Sunday": "रविवार",
          "currentstatus": "आपकी वर्तमान स्थिति",
          "completedTask": "कार्य पूरा हो गया है",
          "completedNotTask": "कार्य पूरा नहीं हुआ",
          "upcomingTask": "आगामी कार्य",
          "minggu": "सप्ताह",
          "hari": "दिन",
          "vegetatif": "वनस्पतिक",
          "taskList": "कार्य सूची",
          "laporanST1": "आपके पास हैं ",
          "laporanST2": "अरिपोर्ट नहीं किए गए कार्य",
          "saveAlert":
              "क्या आप सुनिश्चित हैं कि प्रदान की गई सभी जानकारी सही है?",
          "attachFile": "रसीद जोड़ें",
          "wordLimit": "अक्षर केवल",
          "doneAndNext": "किया और अगला",
          "noAgain": "फिर भरें",
          "sure": "मुझे पक्का है!",
          "errorSavingAssignment": "कार्य सहेजने के दौरान एक त्रुटि आई है।",
          "congratulation1": "महान",
          "congratulation2": "आपने सभी रिपोर्ट्स को पूरा कर लिया है",
          "profileUploadError": "फ़ाइल 500 KB से कम या बराबर होनी चाहिए",
          "gardenCondition": "कुल स्थिति",
          "checkInternet": "इंटरनेट कनेक्शन की जाँच करें",
          "Lot": "खेत",
          "changelot": "दूसरे लॉट पर बदलें",
          "done": "हो गया",
          "changelotalertText": "निम्नलिखित लॉट/ज़ोन में बदलें",
          "addLotNumber": "लॉट नंबर जोड़ें",
          "deleteMessage": "यह संदेश हटा दिया गया है",
          "deleteAlert": "संदेश हटाएं?",
          "deleteSubAlert": "यह संदेश इस चैट से स्थायी रूप से हटा दिया जाएगा।",
          "delete": "हटाएं",
          "cancel": "रद्द करें",
          "administratorTitle": "सत्र समाप्त हो गया है!",
          "administratorSubTitle":
              "सत्र समाप्त हो गया है। आगे के विवरण के लिए कृपया अपने प्रशासक से संपर्क करें।",
          "administratorTitleError": "सर्वर में समस्या!",
          "administratorSubTitleError":
              "त्रुटि!!!!!! आगे के विवरण के लिए कृपया अपने प्रशासक से संपर्क करें।",
          "ok": "ठीक है",
          "loading": "लोड हो रहा है",
          "checkAllDetails": "सभी विवरण देखें",
          "wrongOTP": "सही OTP की आवश्यकता है। कृपया सटीक जानकारी प्रदान करें।",
          "choose": "चुनें",
          "headingChooseLanguage": "हमें आपकी पसंदीदा भाषा बताएं",
          "hi": "हिंदी",
          "en": "अंग्रेज़ी",
          "te": "తెలుగు",
          "chooseLanguage": "भाषा चुनें",
          "data": "डेटा",
          "chat": "चैट",
          "dashboard": "डैशबोर्ड",
          "didNtSelectFile": "अभी तक कोई फ़ाइल नहीं चयन की गई है।",
          "fieldId": "फ़ील्ड नंबर",
          "askAbout": "अपनी फ़ील्ड्स के बारे में कुछ भी पूछें",
          "startTheChat":
              "स्वागत है! आज ही चैट शुरू करें और जुड़ें, सवाल पूछें, या विचार साझा करें। हमारे साथ मायने वाले वार्तालाप में शामिल हों।",
          "typeHere": "यहाँ टाइप करें...",
          "noSeasonFound":
              "क्षमा करें, आपकी कृषि गतिविधि के लिए पिछले या वर्तमान मौसम की जानकारी नहीं मिली।",
          "selectMainTask": "मुख्य कार्य चुनें और तिथि अपडेट करें",
          "probabilityOfPrEc": "पूर्वानुमान पूर्वानुमान",
          "precipitation": "वर्षा",
          "windSpeed": "हवा की गति",
          "windDirection": "हवा की दिशा",
          "cloudCover": "बादल कवर",
          "clouds": "बादल",
          "relativeHumidity": "सापेक्ष आर्द्रता",
          "humidity": "आर्द्रता",
          "soilTemperature_0to10cm": "मृदा तापमान_0to10cm",
          "soilTemperature": "मृदा तापमान",
          "globalRadiationSensibleHeatFlux":
              "वैश्विक प्रकाश - सुसमीक्षात्मक ऊष्मा स्राव",
          "globalRadiation": "वैश्विक प्रकाश",
          "deltaT": "डेल्टा टी (°)",
          "forecast": "पूर्वानुमान",
          "welcomeHome": "स्वागत है!",
          "howCanHelpYou": "मैं आपकी कैसे सहायता कर सकता हूँ?",
          "setting": "सेटिंग",
          "delete_my_account": "मेरा खाता हटाएं",
          "are_you_sure_to_delete": "क्या आप हटाने के लिए सुनिश्चित हैं?",
          "socialMedia": "सोशल मीडिया पेजेस",
          "probabilityOfPrEcShow": "Probability of Prec.",
          "precipitationShow": "Precipitation",
          "windSpeedShow": "Wind speed",
          "windDirectionShow": "Wind direction",
          "cloudCoverShow": "Cloud cover",
          "cloudsShow": "Clouds",
          "relativeHumidityShow": "Relative humidity",
          "humidityShow": "Humidity",
          "soilTemperature_0to10cmShow": "soiltemperature_0to10cm",
          "globalRadiationSensibleHeatFluxShow":
              "Global radiation - Sensible Heat Flux",
          "deltaTShow": "Delta T (°)",
          "broadCastChannel": "प्रसार चैनल",
          "are_you_sure_to_change_image": "प्रोफ़ाइल छवि अद्यतन की पुष्टि करें",
          "change_image_description":
              "अपनी प्रोफ़ाइल बढ़ाएँ! अपनी ऑनलाइन उपस्थिति को निजीकृत करने के लिए अपनी छवि की पुष्टि करें और अपडेट करें। 🌟",
          "mobileNumberCorrectFormat": "सही 10 अंकों का संपर्क नंबर दर्ज करें",
          "noForecastDataFound1":
              "कृपया मौसम पूर्वानुमान देखने के लिए स्क्रीन के शीर्ष पर उपलब्ध ड्रॉपडाउन मेनू से",
          "noForecastDataFound2": "का चयन करें। धन्यवाद।",
          "alerts": "चेतावनी",
          "warning": "सावधानी",
          "notification": "सूचना",
          "soilAlert": "मिट्टी की चेतावनी",
          "stationData": "मृदा डेटा स्नैपशॉट",
          "diseaseAlert": "रोग चेतावनी",
          "noStationDataFound":
              "क्षमा करें, कोई स्टेशन डेटा नहीं मिला। अद्यतन जानकारी के लिए कृपया बाद में दोबारा जाँचें। धन्यवाद।",
          "about_usD1":
              "यह एप्लिकेशन टेक्निको कॉर्प की ओर से पूरी तरह आंतरिक परीक्षण उद्देश्यों के लिए विकसित किया गया है।",
          "about_usD2":
              "यदि आपका कोई प्रश्न या चिंता है तो कृपया grish.gautam@technico.org.in पर लिखें।",
          "soilData": "मृदा आँकड़े",
          "details": "विवरण",
          "featureComingSoon":
              "नोट: यह सुविधा जल्द ही आ रही है.\nकृपया अनुकूलित रहें।",
          "diseaseAlertDataFound1":
              "रोग चेतावनी देखने के लिए कृपया स्क्रीन के शीर्ष पर उपलब्ध ड्रॉपडाउन मेनू से",
          "diseaseAlertDataFound2": "का चयन करें। धन्यवाद।",
          "dataRefreshing": "लोड हो रहा है...",
          "today": "आज",
          "yesterday": "कल",
          "diseaseModel": "रोग मॉडल",
          "severityValue": "गंभीरता मूल्य:",
          "sprayValue": "स्प्रे मूल्य:",
          "sprayInterval": "स्प्रे अंतराल:",
          "diseaseSeverity": "रोग गंभीरता मूल्य",
          "min": "न्यूनतम",
          "max": "अधिकतम",
          "days": "दिन",
          "chatDefaultBroadCast": "फ़ील्ड के बारे में व्यवस्थापक से सभी अपडेट",
          "noFieldsAreAttachWithYou":
              "आप अभी तक चैट नहीं कर सकते! इस समय आपकी प्रोफ़ाइल से कोई फ़ील्ड संलग्न नहीं है.",
          "noRecharge": "कोई रिचार्ज नहीं",
          "purchasedOn": "खरीद तिथि: ",
          "simDetails": "सिम विवरण",
          "active": "सक्रिय",
          "expired": "समाप्त",
          "plan": "प्लान",
          "expireOn": "समाप्ति तिथि",
          "verify": "सत्यापित करें",
          "simAlerts": "सिम अलर्ट",
          "simAlertDataFound1":
              "क्षमा करें, कोई सिम डेटा नहीं मिला। कृपया अद्यतन जानकारी के लिए बाद में जांचें। धन्यवाद।",
          "sign_in": "साइन इन करें",
          "": "",
        },
        "en": {
          "appName": "Technico Corp",
          "login": "Login",
          "email": "Email",
          "password": "Password",
          "remember_me": "Remember me",
          "forgot_password": "Forgot Password",
          "enter_email_address": "Enter Email Address",
          "enter_valid_email": "Enter Valid Email",
          "enter_password": "Enter Password",
          "password_should_be":
              "The password must have at least 8 characters, including one letter each in upper and lower capital, 1 special character and 1 number.",
          "create_an_account": "Create an Account",
          "signup": "SignUp",
          "continue_as_a": "Continue as a",
          "guest": "Guest",
          "OR": "OR",
          "name": "Name",
          "create_account": "Create Account",
          "confirm_password": "Confirm Password",
          "serverError": "Server Error. Try Again Later",
          "accountAlreadyExist": "The account already exists for that email.",
          "accountNotExist": "No user found for that email.",
          "wrongPassword": "Wrong password provided for that user.",
          "comingSoon": "Coming Soon",
          "home": "Home",
          "news": "News",
          "settings": "Setting",
          "search": "Search",
          "dark_theme": "Dark Theme",
          "are_you_sure_to_delete_account": "Are You Sure to Delete Account",
          "are_you_sure_to_log_out": "Are You Sure to Log out",
          "it_will_remove_your_all_information":
              "It will Remove your all Information",
          "no": "No",
          "yes": "Yes",
          "delete_account": "Delete Account",
          "internetIssue": "Try Connecting to Network or Try Again Later",
          "log_out": "Logout",
          "noInternetImage":
              "No Internet Connection Available. Refresh to reload screens",
          "noDataFound": "No Data Found",
          "already_have_account": "Already have account",
          "enter_first_name": "Enter First Name",
          "enter_confirm_password": "Enter Confirm Password",
          "password_did_not_match": "Password did not match",
          "error": "Error",
          "termsAndConditions1": "ByContinuing you agree to the",
          "termsAndConditions2": " Terms & Conditions",
          "about_us": "About Us",
          "about_us_Head": "Technico Corp",
          "skip": "Skip",
          "loginScreen1": "Welcome!",
          "loginScreen2": "Please fill in a profile to start the application",
          "loginScreen3": "Add a picture",
          "mobilenumberhint": "Phone No.",
          "mobilenumbererror": "Enter Phone No.",
          "editimage": "Please select your image source:",
          "cameraCapture": "Take a picture",
          "galleryCapture": "Select From Your Gallery",
          "buildnamebar1": "You have ",
          "buildnamebar2": "task ",
          "buildnamebar3": "which has not been reported",
          "highTemperature": "Temperature above 40 degrees",
          "highrain": "Thunderstorm, with Rainfall more than 8 mm",
          "alert": "Warning: ",
          "weather": "Weather",
          "sunny": "It\"s sunny",
          "rumusan": "Summary",
          "important": "Important Contents",
          "report": "Report now",
          "laporantugas": "Task Report",
          "beritaterkini": "Latest\n news",
          "pencapaianpetani": "Farmer Achievements",
          "peringtantugas": "Task\n Reminder",
          "ramalancuaca": "Weather\n forecast",
          "jomberbual": "Let\"s\n talk",
          "logout": "Log Out",
          "returnHomePage": "Return to Home Page",
          "startconvo": "Start a conversation",
          "enterSomethingError": "Enter Something",
          "givePermission": "Please Give Permission",
          "recordingwarning": "Hold to Record, then press send",
          "beritarasmi": "Official",
          "beritalain": "Other",
          "beritarasmiShow": "Official",
          "beritalainShow": "Other",
          "morning": "Morning",
          "evening": "Evening",
          "Monday": "Monday",
          "Tuesday": "Tuesday",
          "Wednesday": "Wednesday",
          "Thursday": "Thursday",
          "Friday": "Friday",
          "Saturday": "Saturday",
          "Sunday": "Sunday",
          "currentstatus": "Your Current Status",
          "completedTask": "The task has been completed",
          "completedNotTask": "Task not completed",
          "upcomingTask": "Upcoming Task",
          "minggu": "Week",
          "hari": "Day",
          "vegetatif": "Vegetative",
          "taskList": "List of tasks",
          "laporanST1": "You have ",
          "laporanST2": "unreported tasks",
          "saveAlert": "Are you sure all the information provided is correct ?",
          "attachFile": "Attach Receipt",
          "wordLimit": "letters only",
          "doneAndNext": "Done & Next",
          "noAgain": "Fill Again",
          "sure": "I'm sure!",
          "errorSavingAssignment":
              "An error occurred while saving the assignment.",
          "congratulation1": "Great",
          "congratulation2": "You have finished completing all reports",
          "profileUploadError": "File must be less or equal to 500 KB",
          "gardenCondition": "Overall Condition",
          "checkInternet": "Check Internet Connection",
          "Lot": "Lot",
          "changelot": "Change Other Lot",
          "done": "Done",
          "changelotalertText": "Change to the following Lot/Zone",
          "addLotNumber": "Add Lot Number",
          "deleteMessage": "This Message is deleted",
          "deleteAlert": "Delete Message?",
          "deleteSubAlert":
              "This Message will be permanently deleted from this chat.",
          "delete": "Delete",
          "cancel": "Cancel",
          "administratorTitle": "Session Over!",
          "administratorSubTitle":
              "Session is Over. For Further Details Please Contact to your Administrator.",
          "administratorTitleError": "Server Problem!",
          "administratorSubTitleError":
              "Error!!!!!! For Further Details Please Contact to your Administrator.",
          "ok": "Okay",
          "loading": "Loading",
          "checkAllDetails": "Check All Details",
          "wrongOTP": "Correct OTP needed. Kindly provide the accurate one.",
          "choose": "Choose",
          "headingChooseLanguage": "Help us know your preferred Language",
          "hi": "हिंदी",
          "en": "English",
          "te": "తెలుగు",
          "chooseLanguage": "Choose Language",
          "data": "Data",
          "chat": "Chat",
          "dashboard": "Dashboard",
          "didNtSelectFile": "No file chosen yet.",
          "fieldId": "Field No.",
          "askAbout": "Ask Anything about your Fields",
          "chatDefaultBroadCast": "All Updates from admin about field",
          "startTheChat":
              "Welcome! Start a chat today to connect, ask questions, or share thoughts. Engage in meaningful conversations with Us.",
          "typeHere": "Type here...",
          "noSeasonFound":
              "Sorry, no season information found for your farming activity during the last or current season.",
          "selectMainTask": "Select Main Task and Update Date",
          "probabilityOfPrEc": "Probability of Prec.",
          "precipitation": "Precipitation",
          "windSpeed": "Wind speed",
          "windDirection": "Wind direction",
          "cloudCover": "Cloud cover",
          "clouds": "Clouds",
          "relativeHumidity": "Relative humidity",
          "humidity": "Humidity",
          "soilTemperature_0to10cm": "soiltemperature_0to10cm",
          "soilTemperature": "Soil Temperature",
          "globalRadiationSensibleHeatFlux":
              "Global radiation - Sensible Heat Flux",
          "globalRadiation": "Global radiation",
          "deltaT": "Delta T (°)",
          "forecast": "Forecast",
          "welcomeHome": "Welcome!",
          "howCanHelpYou": "How can I help you?",
          "setting": "Setting",
          "delete_my_account": "Delete my Account",
          "are_you_sure_to_delete": "Are you sure to delete?",
          "socialMedia": "Social Media Pages",
          "hello": "Hello",
          "probabilityOfPrEcShow": "Probability of Prec.",
          "precipitationShow": "Precipitation",
          "windSpeedShow": "Wind speed",
          "windDirectionShow": "Wind direction",
          "cloudCoverShow": "Cloud cover",
          "cloudsShow": "Clouds",
          "relativeHumidityShow": "Relative humidity",
          "humidityShow": "Humidity",
          "soilTemperature_0to10cmShow": "soiltemperature_0to10cm",
          "globalRadiationSensibleHeatFluxShow":
              "Global radiation - Sensible Heat Flux",
          "deltaTShow": "Delta T (°)",
          "broadCastChannel": "BroadCast Channel",
          "are_you_sure_to_change_image": "Confirm Profile Image Update",
          "change_image_description":
              "Enhance your profile! Confirm and update your image to personalize your online presence. 🌟",
          "mobileNumberCorrectFormat": "Enter correct 10 Digit Contact Number",
          "noForecastDataFound1": "Please select",
          "noForecastDataFound2":
              "from the dropdown menu available on the top of the screen for viewing the weather forecast. Thank you.",
          "diseaseAlertDataFound1": "Please select",
          "diseaseAlertDataFound2":
              "from the dropdown menu available on the top of the screen for viewing the Disease Alert. Thank you.",
          "noStationDataFound":
              "Apologies, no station data found. Please check back later for updated information. Thank you.",
          "alerts": "Alerts",
          "warning": "Warning",
          "notification": "Notification",
          "soilAlert": "Soil Alert",
          "stationData": "Soil Data Snapshot",
          "diseaseAlert": "Disease Alert",
          "details": "Details",
          "about_usD1":
              "This application has been developed on behalf of Technico Corp, purely for internal testing purposes.",
          "about_usD2":
              "Please write to girish.gautam@technico.org.in in case you have any questions or concern.",
          "soilData": "Soil Data",
          "featureComingSoon":
              "Note: This feature is coming soon.\nPlease stay tuned.",
          "dataRefreshing": "Loading...",
          "youHaveImage": "Photo",
          "youHaveAudio": "Audio",
          "today": "Today",
          "yesterday": "Yesterday",
          "diseaseModel": "Disease Models",
          "severityValue": "Severity Value:",
          "sprayValue": "Spray Value:",
          "sprayInterval": "Spray Interval:",
          "diseaseSeverity": "Disease Severity Value",
          "min": "Min",
          "max": "Max",
          "days": "Days",
          "percentage": "Percentage (%)",
          "noFieldsAreAttachWithYou":
              "You can't chat yet! No fields are attached to your profile at the moment.",
          "noRecharge": "No Recharge",
          "purchasedOn": "Purchased on: ",
          "simDetails": "Sim Details",
          "active": "Active",
          "expired": "Expired",
          "plan": "Plan",
          "expireOn": "Expire on",
          "verify": "Verify",
          "simAlerts": "Sim Alert",
          "simAlertDataFound1":
              "Apologies, no sim data found. Please check back later for updated information. Thank you.",
          "sign_in": "Sign In",
          "farmer": "Farmer",
          "user": "User",
          "": "",
        }
      };
}
